# .github/workflows/update_students.yml
name: Update Student Repositories

on:
  push:
    branches:
      - main

jobs:
  update-students:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install GitHub CLI and Git
      run: |
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
        sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
        sudo apt update
        sudo apt install gh git -y

    - name: Authenticate GitHub CLI
      env:
        GITHUB_TOKEN: ${{ secrets.CLASSROOM_TOKEN }}
      run: |
        gh auth status

    - name: Get List of Student Repositories
      id: get_repos
      env:
        GITHUB_TOKEN: ${{ secrets.CLASSROOM_TOKEN }}
      run: |
        echo "Fetching student repositories..."
        gh api orgs/cmse822/repos --paginate --jq '.[] | select(.name | startswith("cmse822-ss25-")) | .name' > student_repos.txt
        echo "Student repositories found:"
        cat student_repos.txt

    - name: Copy Template to Student Repositories
      env:
        GITHUB_TOKEN: ${{ secrets.CLASSROOM_TOKEN }}
      run: |
        TEMPLATE_REPO="cmse822/cmse822-codex-ss25"
        TEMPLATE_BRANCH="main"

        while read repo; do
          echo "Processing repository: $repo"

          # Clone the student repository
          git clone "https://${GITHUB_TOKEN}@github.com/cmse822/$repo.git"
          cd "$repo"

          # Set up Git credentials
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"

          # Create a unique update branch
          NEW_BRANCH="update-from-template-$(date +%s)"

          # Remove old update branch if it exists
          git branch -D "$NEW_BRANCH" 2>/dev/null || true
          git push origin --delete "$NEW_BRANCH" 2>/dev/null || true

          # Fetch the latest template branch and hard reset student repo
          git remote add template "https://github.com/$TEMPLATE_REPO.git"
          git fetch template
          git checkout -b "$NEW_BRANCH"
          git reset --hard template/$TEMPLATE_BRANCH

          # Push the new update branch to the student repository
          git push origin "$NEW_BRANCH" --force

          # Create a pull request from the new update branch to the student's main branch
          gh pr create --repo cmse822/$repo \
            --head "$NEW_BRANCH" \
            --base main \
            --title "Update from Template Repository" \
            --body "This PR updates the student repository with the latest changes from the template. Review and merge to stay up-to-date." || {
              echo "Error: Failed to create PR in $repo"
              cd ..
              rm -rf "$repo"
              continue
            }

          echo "Pull request created for repository: $repo"
          cd ..
          rm -rf "$repo"  # Clean up after processing

          sleep 2  # Prevent rate-limiting issues

        done < student_repos.txt
